//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTAS_TB
    {
        public int Nota_ID { get; set; }
        public int Notas_Cuenta_ID { get; set; }
        public string Titulo { get; set; }
        public string Cuerpo { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public string Estado { get; set; }
    
        public virtual CUENTAS_TB CUENTAS_TB { get; set; }
    }
}
